### PR TITLE
Turn merged PRs purple within GH interface

### PR DESCRIPTION
**Pull request by ruyadorno**
This tweaks the script to force-push the squashed and
metadata-annotated commit back into the user's branch so that once we
land it in our `main` branch their PR will properly be merged with a
purple icon as expected by most users of the platform.

### CODE REVIEW

**Comment by ruyadorno** [comment]
Also adds a `pull update <number>` workflow for cases when we ammend commit / edit things and want to update that target remote again.

**Comment by isaacs** [comment]
This is rad.

**Comment by ruyadorno** [comment]
cc @ljharb 🟣 there you go! 💜

**Comment by ljharb** [comment]
@ruyadorno ❤️ ❤️ ❤️  i owe you some beverages if travel ever becomes a thing again

**Pull request merged**
